adminUser:
  password: vault:pr-486-13arc/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-486-13arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-486-13arc/prow:hmacToken
segmentWriteKey: vault:pr-486-13arc:segmentWriteKey
